# Example GitHub Actions workflow for deploying Datadog resources
# Copy to .github/workflows/datadog.yml to use

name: Deploy Datadog Monitoring

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/datadog/**'
      - 'datadog-dashboard.json'
      - '.github/workflows/datadog.yml'
  workflow_dispatch:

env:
  TF_VERSION: '1.6.0'
  AWS_REGION: 'us-east-1'

jobs:
  terraform:
    name: Deploy Datadog Resources
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform/datadog

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        env:
          # If using S3 backend, add AWS credentials
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
          TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
          TF_VAR_datadog_api_url: "https://api.us5.datadoghq.com/"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
          TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
          TF_VAR_datadog_api_url: "https://api.us5.datadoghq.com/"

      - name: Comment PR with Dashboard URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan 📊

            <details><summary>Show Plan</summary>

            \`\`\`
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

# Required GitHub Secrets:
# - DATADOG_API_KEY: Your Datadog API key
# - DATADOG_APP_KEY: Your Datadog Application key
# - AWS_ACCESS_KEY_ID: (Optional) For S3 backend
# - AWS_SECRET_ACCESS_KEY: (Optional) For S3 backend
#
# To add secrets:
# 1. Go to your repo Settings → Secrets and variables → Actions
# 2. Click "New repository secret"
# 3. Add each secret with the name and value
